branches:
  only:
  - master
language: java
jdk:
- oraclejdk8
before_install:
- git config user.name "$GIT_NAME"
- git config user.email "$GIT_EMAIL"
- git config --global push.default simple
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials
script: ./gradlew --info clean asciidoctor
after_success:
- ./push.sh
notifications:
  email:
  - baruchs@jfrog.com
  on_success: always
  on_failure: always
env:
  global:
  - secure: GVZlSpAHILCJm1+OFaBTFy6l8vsIAtsWvxhz9dTkF5bELlgq75nDiKvtt6UKki0oBeZcXriCKOvNjsgiU5WgtAeH+fm5AP0zjurlFEvJedu3aqiJDwbZaOCPStXQPyxEzzTprHDsYkuODmROfXAtGTssQbYjNTcXJDJhtKrKw56AIo74NvN6mVz0IUYCDre7TZvSuBVb9e3TqqFTcye3fUqsU24SQcnM12WhlaETOWh6TAljDVdAd9ZCIDilxXn6m9BVMr/kdH1nTFXpSpxKel5xhyTqVdFQo5hGFsTYkn3smsZLjpahOBWgKJ6il9utALo71GQ2x0jM/etpZxM2OlgyQi27z+itrQ8kzovgvOOZDw24p9R0ZGR7SmGTMwFi5CSWf5i8h/xkyBJdgf63NkP3T7KbPUcKkuXH6lGtLV2QEju4RHmN7wn4884cF/ejMO4KzYYrXcf+QZuGhNEzzTkPQMLvugMYu2Q19h6c86LwXgpRl9WZfx9N2OVlpUlLc0Y9lY+W9fJgeha3crcKoMOJjagrE0GS3B7CyuDSUMv7cSLA2Je5SEA4bfiuCMOucW/8p/Im57HoqEFw6CI+s2eZxwsIaMl1sCNFeQ5+8g7/wU51M3Xj0AP8SFm4PettG3Q7cTpw+rZ8dazKAOUo2l8pJxM2CAFvt1ajUd6ghU4=
  - secure: AoFq0FsusoI4/F7Dx1RDKfr/qJ+ICxbuJPT4xYYMnAw8z87uD7YF5B3keM9qUVga/pD7j20e6tpJjhiN6QpJBb747iq1v44NzWIxBeof8sMCo2gAMW4NGGAapT3+qP/M8TFtCk5uzct08ME2nFSWkNnWxlVadzMPmUzwGf1uIsU1lRilbnn8JMQltsYy7mFsiUwSQMfPNN/J9ZGnKyD4cnmWfOmF3Lk3mmjH2swNXWlNUlpQGKIfgWquASM66fJYonRYHjL1GVGHYNRo6zrO6cvBXbZozWNieIo0f3obhFcJTlpZ3xXGl/03/nxLGu4wZrp8m6lQS7cW8tMaFCb6fu3V8degMos1lNF4svnezT2zs9EsJHQLHMalc8S6ZzUyrwwFLfLNjEMMOSZHxsbtZTx7mN0kBPKBKhsLM4mNmT4Ux+KykKXU+zfmmo7Gw0Wl9tncXMt114OE7yrXcpI7jZRwZqqyMgu6XiJST8z44UAta4sArikwcgAMNTQbzoIQ+1GIyQ0dAEt0JDVmVnO0jTMu5yytoH89MmeMBrnM+s4raBfGFrPXySP2He5+hXTngMVNElXf51Sk2BE6H5H05rj5rUbfYs0dI+C0Z5evj9GBbo4TnjWnJRXJCUKjn5WkswBxNC4m7YjdhZzTcYtibCW78Z2RFeK74yV5G0UQBzw=
  - secure: HTBT4D7NUqo2IvsKGBWdC4jS+k+sBccmtCk1OXl+svkmorwMTIOsc5tpjv9rJo/qikqfdlEiJ53/utwCHkQzNwa2ZGsulzLGvKznLc1n/vlAvPJs2WbM72iwktT/61uFh2wjL05IIQ6zwNV+xYlQStz6/fB8VeJHH7M24NjlhJ7+AulZuqfuVT9SMVA6joMtLFHRkkmLEuwkGHxFMhlr1AdyonyczDOlteUcYC4Vt8lOEsFjQGngNA9ZnN1dbbgHCMxWlu3a1tRC87me2zU5XoIlxadwNPlVQ8uQoOEx3lm+3i7yvszzBYrQQNnqoe2sdHOaVgO4fJPizzeR7S/D+doyzJrlARTlMpWg0NPZwFvNsBkqze3rLrUFC5lA8itw/UesodRH3pUNFc4hc3rBx82p72kwEsVl9rZJuqdYbx/WSUB8Kz8aB5dec/muzm6+06bBMLb3SsxYuEN85qH5kXLll+qKr85P79S/oHmv/BBL/XGRrER3WloMXzQVjMMCtFNDxfYNqIbeN8mRt43WO4yHjU4BpQUByRpdnlMjt3GD4HAh3BnH/Yz/reb9vy8aH9RYtnKFP1SFkKhsNJD62neBb5SkJkCmwIghnO9SAzCg1lFtOZ+gCEVsjfYACp+tG9rAOrYQ2U8kpHQLzruRczdKkfVHLtADgZvT8uB0A0w=
