branches:
  only:
  - master
language: java
jdk:
- oraclejdk8
before_install:
- git config user.name "$GIT_NAME"
- git config user.email "$GIT_EMAIL"
- git config --global push.default simple
- git config credential.helper "store --file=.git/credentials"
- echo "https://$GH_TOKEN:@github.com" > .git/credentials
script: ./gradlew clean asciidoctor
after_success:
- ./push.sh
notifications:
  email:
  - baruchs@jfrog.com
  on_success: always
  on_failure: always
env:
  global:
   - GIT_NAME=binary-repos-matrix-bot GIT_EMAIL=binary-repos-matrix-bot@users.noreply.github.com
    secure: GVZlSpAHILCJm1+OFaBTFy6l8vsIAtsWvxhz9dTkF5bELlgq75nDiKvtt6UKki0oBeZcXriCKOvNjsgiU5WgtAeH+fm5AP0zjurlFEvJedu3aqiJDwbZaOCPStXQPyxEzzTprHDsYkuODmROfXAtGTssQbYjNTcXJDJhtKrKw56AIo74NvN6mVz0IUYCDre7TZvSuBVb9e3TqqFTcye3fUqsU24SQcnM12WhlaETOWh6TAljDVdAd9ZCIDilxXn6m9BVMr/kdH1nTFXpSpxKel5xhyTqVdFQo5hGFsTYkn3smsZLjpahOBWgKJ6il9utALo71GQ2x0jM/etpZxM2OlgyQi27z+itrQ8kzovgvOOZDw24p9R0ZGR7SmGTMwFi5CSWf5i8h/xkyBJdgf63NkP3T7KbPUcKkuXH6lGtLV2QEju4RHmN7wn4884cF/ejMO4KzYYrXcf+QZuGhNEzzTkPQMLvugMYu2Q19h6c86LwXgpRl9WZfx9N2OVlpUlLc0Y9lY+W9fJgeha3crcKoMOJjagrE0GS3B7CyuDSUMv7cSLA2Je5SEA4bfiuCMOucW/8p/Im57HoqEFw6CI+s2eZxwsIaMl1sCNFeQ5+8g7/wU51M3Xj0AP8SFm4PettG3Q7cTpw+rZ8dazKAOUo2l8pJxM2CAFvt1ajUd6ghU4=
